### ISSUE TITLE
job status blijft op prepared staan

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/InSpider#18]
Na laden van data, in tabel van job, blijft de status op prepared staan

**Comment by stefanvanwouw** [comment]
Dit kan voorkomen als er bijvoorbeeld een nullpointer exception gegooid wordt in de process() methode van de job (e.g. TagProcess, RemoveProcess, etc.). 
Zou in normale operatie niet voor moeten komen. 

Zelf heb ik dit nog nooit ondervonden, heb het vermoeden dat dit met het feit te maken heeft dat we nog fouten in onze job processing code hadden (overlapvalidatie enzo) toen dit geconstateerd werd.

**Comment by annesongithub** [comment]
AttributeMappingDao regel 108 krijg ik lazy initialisation exception van hibernate. Blijkbaar werkt de transactional bij mij niet goed op de getAttributeMapping method.
