### ISSUE TITLE
ThemeConfig#getSchemaName() weg refactoren

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/InSpider#24]
Het zou mooier zijn als deze functie niet nodig is. (komt in master vanuit 7-vaststellen branch).

Een alternatief is om bij het aanmaken van een Tagjob of RemoveJob het schema in een parameter mee te geven. Dit kan door de de annotatie op de domeinklasse (featureclass) uit te lezen.

Hiervoor dient er wat code gerefactored te worden in TagJob/TagProcess en RemoveJob/RemoveProcess

**Comment by reinoldp** [comment]
Kan de TagJob of RemoveJob dit niet zelf uitlezen? Van een parameter op een TagJob of RemoveJob verwacht ik dat dit een te configureren parameter is, terwijl het db schema eigenlijk statisch is.

**Comment by stefanvanwouw** [comment]
Ze kunnen het op dit moment zelf uitlezen door de ThemeConfig instantie te gebruiken die bij de featureset hoort die je tagt/verwijdert. Alleen dit is nog steeds regressiegevoelig.

Vanuit generiek InSpider oogpunt is het schema namelijk niet statisch. Deze is afhankelijk van het thema wat je wilt taggen of waarin de dataset valt die je wilt verwijderen. Het is dus gewoon een parameter die je nodig hebt bij een Tag/RemoveJob. Dat dit in het geval van vrn altijd "vrn" is wil nog niet zeggen dat er niet een domeinklasse kan worden geimplementeerd die @Entity(name="tablenaam", schema="andere_naam_dan_vrn") als annotatie heeft. 

Het refactoren zorgt ervoor dat er in de toekomst niet weer een regressie wordt geintroduceerd, en het is ook netter dan een statische string in het ThemeConfig te stoppen.

**Comment by reinoldp** [comment]
Ik bedoelde met statisch dat het schema per thema vaststaat en mi daarmee geen onderdeel zou moeten zijn van van de parameters van een Job. Vreemd ook om db specifieke configuratie in een Job te zetten. Het schema in de @Entity annotatie zetten klinkt al een stuk logischer, maar ik zie nu dat dit nu als zo is. Kan de TagProcessor (oid) de schema naam niet zelf uitlezen uit die annotatie?

**Comment by stefanvanwouw** [comment]
Het probleem is dat de TagProcess / RemoveProcess klassen op dit moment geen toegang hebben tot de dataset waarmee ze bezig zijn. Ik ga zometeen even kijken of dat op een andere manier kan zodat we wel bij de domein klasse kunnen in de processors.

**Comment by stefanvanwouw** [comment]
Net even met Anne-Ruth besproken. We hebben een oplossing:

- ThemeConfig#getSchemaName() gaat weg.
- De TagJob geeft de themanaam en tag mee als job parameters.
- TagProcess/RemoveProcess halen het schema en de tabel uit de @Entity annotatie. Hiervoor hebben ze het themanaam nodig, welke voor RemoveProcess uit het datasettype gehaald kan worden via de themediscoverer, en voor TagProcess halen we die uit de parameters (want er wordt geen datasettype meegegeven).

**Comment by stefanvanwouw** [comment]
Het werkt met Anne-Ruth haar wijzigingen en mijn wijzigingen uit commit https://github.com/CDS-VRN/InSpider/commit/f89672d72195a6a3ecf692660016f7451e2438b3
