### ISSUE TITLE
Refactor afterJob validation pipeline

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/InSpider#27]
Huidige implementatie
-----------------------------

De feature filters hebben een processFeature() en finish() methode. De eerste is verantwoordelijk voor het verwerken van 1 feature per keer. De finish methode is verantwoordelijk voor zowel het opruimen van resources zoals (database) locks, en het uitvoeren van validatie achteraf.

Probleem
-----------------------------
De finish() methoden hebben te veel verantwoordelijkheden en dit zorgt voor conflicten zoals deadlocks op de database wanneer er een rollback wordt gedaan in de validatie, maar de importfeatureprocessor nog de database lock heeft.

Voorgestelde implementatie
-----------------------------
We voegen een extra methode postProcess() aan de FeatureFilter interface toe die de post processing zoals afterJob validatie voor zijn rekening neemt. Deze methode geeft een boolean terug die aangeeft of het processen (valideren) goed gegaan is of niet. De finish() methode doet alleen nog maar de resource cleanup en wordt vóór de postProcess() methode aangeroepen.

De klassen die gewijzigd moeten worden zijn:

- Alle klassen die FeatureFilter implementeren en FeatureFilter zelf.
- ValidateFeatureProcessor voor de aanroep van FeatureFilter#postProcess().
- AbstractValidator om de afterJob methode naar de AbstractValidator.Reporter te laten loggen ipv een RuntimeException te gooien. 
- AbstractValidator.Reporter om te zorgen dat er geen error messages worden verwijdert bij afterJob logging (standaard haalt hij de tweede weg vanwege duplicate keys die worden aangeleverd via Reporter#reportValidationError(), dat is nu conditioneel).
- Het streven is om de exceptions die validatiefouten aangeven te minimaliseren en deze door een boolean return value te vervangen, terwijl er daarvoor naar de event logger wordt geschreven wat de fout is.

**Comment by erikorbons** [comment]
Prima voorstel! Als dit haalbaar is om te implementeren zou ik zeggen: doen.
