### ISSUE TITLE
Aanmaken van een nieuwe dataset met ongeldig UUID geeft een exception

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/InSpider#28]
Bij het aanmaken van een nieuwe dataset waarbij een ongeldige UUID wordt ingevuld (onbestaand in PGR) dan komt er een exception terug bij het opslaan. Het opslaan blijkt daarna wel gelukt te zijn.

**Comment by stefanvanwouw** [comment]
Dit komt ook voor als je whitespace voor of achter je xsd/gml URL stopt. METADATA_NOTFOUND

**Comment by stefanvanwouw** [comment]
Is dit trouwens niet standaard CDS functionaliteit? Altijd al zo geweest, die stack traces...

**Comment by stefanvanwouw** [comment]
Besloten in hangout van vanmorgen: Standaard CDS functionaliteit
