### ISSUE TITLE
PSQL fout bij importeren

### ISSUE THREAD

**Issue by Rosanvw** [CDS-VRN/InSpider#34]
Bij het importeren van dataset:  	http://ftp.geodan.nl/vrn/data/test/geometrie/test.gml?request=GetFeature&typename=GebiedBeheerNM&service=WFS&version=1.1.0 

Kreeg ik de volgende foutmelding:
Fout 	Fout bij parsen Features. Oorzaak: PSQLException: ERROR: permission denied for relation gebiedbeheer_landelijk

**Comment by stefanvanwouw** [comment]
@erikorbons even dit script runnen op test (afgelopen week had ik dit pas geconstateerd en gefixt, dat inspire geen rechten heeft op de vrn tabellen): https://raw.githubusercontent.com/CDS-VRN/CDS-BIJ12/master/vrn-themes/src/main/sql/7_grant_tables.sql

**Comment by stefanvanwouw** [comment]
Als het goed is komt deze bug al niet meer voor op de acceptatie omgeving 2.2-vrn-0.2

**Comment by erikorbons** [comment]
Testomgeving moet worden bijgewerkt met de nieuwe Docker images zodat deze bug ook daar verholpen is.
