### ISSUE TITLE
Validatie melding kan beter

### ISSUE THREAD

**Issue by Rosanvw** [CDS-VRN/InSpider#35]
Bij negatief resultaat van de validatie of een geometrie op of binnen een gebied van een bronhouder ligt is de melding dat de geometrie niet binnen het bronhouder gebied ligt. Beter is als er zou staan niet binnen of op het bronhouder gebied.

**Comment by stefanvanwouw** [comment]
De melding is nu: De meegegeven geometrie valt niet geheel binnen het gebied van de bronhouder.

Het mag er maximaal 1 meter buiten liggen (dat is instelbaar). In de praktijk mag het dus ook de grens overschreiden, maar dan wel minimaal. In theorie mag het de grens niet overschreiden. Ik denk dat de melding zoals het nu is duidelijker is dan de "of op het bronhouder gebied".
