### ISSUE TITLE
Configuratie fout?

### ISSUE THREAD

**Issue by Rosanvw** [CDS-VRN/InSpider#36]
Forbidden

Als ik op de link: klik hier voor de metadataset klik achter een eigen dataset (die zonder metadata is geupload) krijg ik de volgende melding:

You don't have permission to access /vrn/data/test/geometrie/test_invalidcoordinates.gml;http://ftp.geodan.nl/vrn/data/test/geometrie/geometries-test.xsd;GebiedBeheerNM on this server.

**Comment by stefanvanwouw** [comment]
Normaal zou je dan naar de WFS gaan. Maar omdat we met de "truc" werken probeert je browser de ; samengevoegde url op te vragen en die bestaat natuurlijk niet.
