### ISSUE TITLE
Mogen provincies valideren en importeren in gebiedbeheer_provinciaal?

### ISSUE THREAD

**Issue by Rosanvw** [CDS-VRN/InSpider#37]
Ik heb een dataset proberen te valideren onder Noord-Brabant/gebiedbeheer_provinciaal, maar kreeg onderstaande fout:
Fout 	Fout bij parsen Features. Oorzaak: PSQLException: ERROR: permission denied for relation gebiedbeheer_provinciaal 

Gevoelsmatig zou ik zeggen dat provincies gebruik moeten maken van dit thema en niet van gebiedsbeheer_landelijk, dat lijkt me meer voor landelijke bronhouders.

**Comment by stefanvanwouw** [comment]
De definitie is juist andersom en heel verwarrend:

1. De landelijke bronhouders uploaden "klad"data naar *_provinciaal.
2. De provinciale bronhouders downloaden deze "klad" data via de WFS (3) die Huub heeft gemaakt. Ze krijgen alleen de features die binnen hun provincie liggen of daarmee overlappen (hier voorzie ik nog een probleem, maar zo is de workflow nu). Ze verrijken het dan in hun eigen GIS pakket.
3. De provinciale bronhouders uploaden hun definitieve verrijkte versie naar *_landelijk. Hier zijn de eisen veel stricter, zoals de check dat al de features BINNEN hun provincie moeten vallen.
4. De landelijke datasets zijn ook via een WFS van Huub beschikbaar (3).
5. Als er een landelijk thema wordt vastgesteld komt deze ook weer in een WFS van Huub : Gebied(Beheer|Inrichting|Verwerving)LandelijkVastgesteld.

In totaal zijn er dus 9 WFS endpoints.

**Comment by stefanvanwouw** [comment]
Zie issue #34

**Comment by erikorbons** [comment]
@Rosanvw, @stefanvanwouw: het lijkt me dat deze dicht kan? De gerelateerde #34 is inmiddels opgelost voor acc en issue CDS-VRN/CDS-Assembly#25 gaat over het bijwerken van de testomgeving zodat dit in test ook niet meer speelt.
