### ISSUE TITLE
NAW panel in admin aanpassen

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/InSpider#41]
Door de mogelijkheid om bronhouders te kunnen bewerken is het NAW paneel in de huidige vorm niet meer geschikt. Een gebruiker kan bij meerdere bronhouders horen.

Uitdaging: gebruikers behoren volgens het nieuwe model niet meer direct tot een bronhouder, maar tot één of meerdere bronhouderthema's. Het bewerken van de NAW-gegevens behorende bij de bronhouder is dus niet meer zo vanzelfsprekend als eerder het geval was.

**Comment by erikorbons** [comment]
Huidige oplossing: een gebruiker mag de NAW-gegevens van een bronhouder beheren als de gebruiker DATABEHEERDER rechten heeft op tenminste één thema van deze bronhouder.

Is dit een acceptabele oplossing? Zo niet, dan zal er langs een andere weg een directere gebruiker <-> bronhouder relatie ge(her)introduceerd moeten worden.

**Comment by stefanvanwouw** [comment]
geen problemen uit GAT of FAT hierover. Dus ik sluit hem.
