### ISSUE TITLE
Beperken functionaliteit beheermodule tot enkel inzien gegevens bij 'alleen lezen' relatie met bronhouder

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/InSpider#5]
Vereist aanpassing interface dao <-> controller

**Comment by erikorbons** [comment]
Aandachtspunten:

- Er is een nieuwe landingpage nodig voor gebruikers die geen rechten hebben op een thema: deze gebruikers mogen momenteel geen enkele pagina van de admin bekijken, maar mogen wel inloggen.
- Er is een mechanisme nodig om te voorkomen dat er een situatie ontstaat waarbij er geen enkele superuser is (bij alle gebruikers het vinkje uitzetten).

**Comment by erikorbons** [comment]
Controllers:
- [ ] AttributeMappingController
- [ ] BAIndexController
- [ ] BronhouderRedirectController
- [ ] CodeListController
- [ ] DatasetController
- [ ] DownloadController
- [ ] DownloadserviceController
- [ ] EtlOverzichtController
- [ ] JobDetailsController
- [ ] MetadataController
- [ ] MonitoringController
- [ ] NawController
- [ ] TagDatasetController
- [ ] VDConfigurationController
- [ ] gebruikersbeheer/AutorisatieController
- [ ] gebruikersbeheer/BronhouderController
- [ ] gebruikersbeheer/GebruikerBeheerController
- [ ] gebruikersbeheer/GebruikersBeheerController

**Comment by erikorbons** [comment]
EtlOverzicht wordt beschikbaar voor gebruikers met rol raadplegen. Deze gebruikers kunnen de ETL-status inzien van geuatoriseerde datasets.

**Comment by stefanvanwouw** [comment]
Deze issue wordt slechts gedeeltelijk meegenomen in release 2.2-vrn-0.3 zoals het er nu uit ziet. Of we taggen hem 0.3 en dan maken we een aparte issue voor het werk wat nog niet helemaal klaar is.
