### ISSUE TITLE
InSpider release 2.2-vrn-0.3 komt niet op Nexus bij bouwen op buildserver

### ISSUE THREAD

**Issue by stefanvanwouw** [CDS-VRN/InSpider#51]

**Comment by stefanvanwouw** [comment]
idem voor 2.2-vrn-0.3.1

**Comment by stefanvanwouw** [comment]
idem voor 2.2-vrn-0.4.1

**Comment by stefanvanwouw** [comment]
idem voor 2.2-vrn-0.4.1 , CDS-BIJ12 omdat de Nexus server down was tijdens het releasen.

**Comment by stefanvanwouw** [comment]
<plugin>
<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>2.4.1</version>
				<configuration>
					<goals>install</goals>
					 
					<autoVersionSubmodules>true</autoVersionSubmodules>
				</configuration>
			</plugin>

**Comment by stefanvanwouw** [comment]
idem 2.2-vrn-0.4.4 , lokaal gebouwd.

**Comment by reinoldp** [comment]
pom aangepast. release  [2.2-vrn-0.5.0](http://buildserver.geodan.nl/viewLog.html?buildId=76877&tab=buildResultsDiv&buildTypeId=vrn_InSpider_Release) werkt.
