### ISSUE TITLE
Versie van project deegree-webservices-cds is onjuist

### ISSUE THREAD

**Issue by erikorbons** [CDS-VRN/InSpider#55]
Versie is nog 2.2, terwijl we momenteel bezig zijn in 2.3-SNAPSHOT

**Comment by erikorbons** [comment]
Lijkt er op dat we hier zelf iets verkeerd hebben gedaan. In de master staat het goed.

**Comment by stefanvanwouw** [comment]
We zijn bezig met 2.2-vrn-1.0-SNAPSHOT, niet 2.3-SNAPSHOT. Die deegree branch was al aangemaakt voordat we het hadden omgenummerd in master.
